"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class battery_state_lcmt(object):
    __slots__ = ["current", "cycle", "SOC", "bms_status", "cell_voltage"]

    __typenames__ = ["int32_t", "int16_t", "int8_t", "int8_t", "int16_t"]

    __dimensions__ = [None, None, None, None, [10]]

    def __init__(self):
        self.current = 0
        self.cycle = 0
        self.SOC = 0
        self.bms_status = 0
        self.cell_voltage = [ 0 for dim0 in range(10) ]

    def encode(self):
        buf = BytesIO()
        buf.write(battery_state_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ihbb", self.current, self.cycle, self.SOC, self.bms_status))
        buf.write(struct.pack('>10h', *self.cell_voltage[:10]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != battery_state_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return battery_state_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = battery_state_lcmt()
        self.current, self.cycle, self.SOC, self.bms_status = struct.unpack(">ihbb", buf.read(8))
        self.cell_voltage = struct.unpack('>10h', buf.read(20))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if battery_state_lcmt in parents: return 0
        tmphash = (0x2394f8796b899cef) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if battery_state_lcmt._packed_fingerprint is None:
            battery_state_lcmt._packed_fingerprint = struct.pack(">Q", battery_state_lcmt._get_hash_recursive([]))
        return battery_state_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

